/*
************************************ 7 mar ************************************
- Think about hopping de channel (gr-gsm)
 */
package gsm.topguw2;

import gsm.topguw2.utils.Utils;
import gsm.topguw.conf.RtlsdrConf;
import gsm.topguw.err.RtlsdrError;
import gsm.topguw.tools.Scanner;
import gsm.topguw.generality.Cell;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author root
 */
public class gui extends javax.swing.JFrame {

    /**
     * VARIABLES
     */
    // rtl sdr configuration
    private RtlsdrConf confRtl = new RtlsdrConf();

    // cells founded in the current use of the program
    private ArrayList<Cell> cells;
    
    // current cell to work with
    private Cell cuCell;

    // workspace
    private File workspace;

    // current cfile 
    private File cfile;

    /**
     * Creates new form gui
     */
    public gui() {
        // workspace location : default = current dir
        workspace = new File(System.getProperty("user.dir"));

        /**
         * ------------- initialise all components ------------------- *
         */
        initComponents();
        // populate the gsm type combobox
        for (String s : Cell.BANDS) {
            gsmtypeSetACellDial1.addItem(s);
        }
        gsmtype.addItem("GSM850");
        gsmtype.addItem("GSM-R");
        gsmtype.addItem("GSM900");
        gsmtype.addItem("EGSM");
        gsmtype.addItem("DCS");
        gsmtype.addItem("PCS");

        // ensure linebreak on error textarea
        errorinformation.setWrapStyleWord(true);
        errorinformation.setLineWrap(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDial = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoabout = new javax.swing.JTextPane();
        closeAboutDial = new javax.swing.JButton();
        configDial = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveconf = new javax.swing.JButton();
        samplerateconf = new javax.swing.JFormattedTextField();
        ppmconf = new javax.swing.JFormattedTextField();
        gainconf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setWorkspace = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        currentWorkspaceLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        errorDial = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorinformation = new javax.swing.JTextArea();
        closerrordialog = new javax.swing.JButton();
        configScanDial = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        gsmtype = new javax.swing.JComboBox<>();
        configurationfromscan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        StartScanBtnDial = new javax.swing.JButton();
        performingScan = new javax.swing.JLabel();
        workspaceLocation = new javax.swing.JFileChooser();
        sniffcellDial = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        cellsForSniffing = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnconf2 = new javax.swing.JButton();
        startSniffing = new javax.swing.JButton();
        cfileLocation = new javax.swing.JFileChooser();
        setACellDial = new javax.swing.JDialog();
        freqLblDial = new javax.swing.JLabel();
        frequencySetACellDial = new javax.swing.JTextField();
        arfcnLblDial = new javax.swing.JLabel();
        arfcnSetACellDial = new javax.swing.JTextField();
        gsmTYpeCellDial = new javax.swing.JLabel();
        gsmtypeSetACellDial1 = new javax.swing.JComboBox<>();
        setACellDialSaveBtn = new javax.swing.JButton();
        sniffACellDial = new javax.swing.JDialog();
        sniffACellLblDial = new javax.swing.JLabel();
        selectCellToSniff = new javax.swing.JComboBox<>();
        startsniffBtnDial = new javax.swing.JButton();
        configurationRtlSniffDial = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        scanCellsBtn = new javax.swing.JButton();
        sniffCellBtn = new javax.swing.JButton();
        setACellBtn = new javax.swing.JButton();
        headerLogo = new javax.swing.JLabel();
        programDescription = new javax.swing.JLabel();
        aboutBtn = new javax.swing.JButton();
        configBtn = new javax.swing.JButton();
        openCfileBtn = new javax.swing.JButton();
        cfileNameLbl = new javax.swing.JLabel();
        performAnalyseBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        activityLog = new javax.swing.JTextPane();

        aboutDial.setTitle("About Topguw");
        aboutDial.setLocation(new java.awt.Point(0, 0));
        aboutDial.setMinimumSize(new java.awt.Dimension(430, 471));
        aboutDial.setModal(true);
        aboutDial.setResizable(false);

        infoabout.setEditable(false);
        infoabout.setBackground(new java.awt.Color(238, 238, 238));
        infoabout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoabout.setContentType("text/html"); // NOI18N
        infoabout.setText("<html>   <head> \t   </head>   <body>     <p style=\"margin:15px;text-align:justify;\">       Topguw is an application that provide GSM datas analysis to try a known-plaintext attack vector on GSM. Topguw uses topguw_api that uses GR-GSM to ensure a good retro-engineering and a flexible work.<br/> </p> \t<br/><br/> <p style=\"margin:2px;\">       <b>Version : 2.0-beta</b><br/>       <b>Author : Enjalbert Bastien (bastien.enjalbert AT gmail.com)</b> </p>         </body> </html> ");
        infoabout.setAutoscrolls(false);
        infoabout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(infoabout);

        closeAboutDial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        closeAboutDial.setText("Close");
        closeAboutDial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAboutDialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutDialLayout = new javax.swing.GroupLayout(aboutDial.getContentPane());
        aboutDial.getContentPane().setLayout(aboutDialLayout);
        aboutDialLayout.setHorizontalGroup(
            aboutDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(aboutDialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeAboutDial)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aboutDialLayout.setVerticalGroup(
            aboutDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(closeAboutDial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configDial.setTitle("Configuration");
        configDial.setMinimumSize(new java.awt.Dimension(378, 413));
        configDial.setModal(true);

        jLabel4.setText("PPM");

        jLabel5.setText("Samplerate");

        jLabel6.setText("Gain");

        saveconf.setText("Save");
        saveconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveconfActionPerformed(evt);
            }
        });

        samplerateconf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        ppmconf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        gainconf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("RTL-SDR Configuration");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Workspace");

        jLabel10.setText("Location");

        setWorkspace.setText("Set directory");
        setWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setWorkspaceActionPerformed(evt);
            }
        });

        jLabel11.setText("Current : ");

        currentWorkspaceLbl.setText(workspace.toString());

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("GSM broadcast cell type");

        jLabel16.setText("Make your choice");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCCH", "BCCH_SDCCH4" }));

        javax.swing.GroupLayout configDialLayout = new javax.swing.GroupLayout(configDial.getContentPane());
        configDial.getContentPane().setLayout(configDialLayout);
        configDialLayout.setHorizontalGroup(
            configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configDialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configDialLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ppmconf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configDialLayout.createSequentialGroup()
                        .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gainconf)
                            .addComponent(samplerateconf)
                            .addComponent(setWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configDialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveconf))
                    .addGroup(configDialLayout.createSequentialGroup()
                        .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addGroup(configDialLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentWorkspaceLbl))
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(configDialLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        configDialLayout.setVerticalGroup(
            configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configDialLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ppmconf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gainconf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(samplerateconf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(setWorkspace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(currentWorkspaceLbl))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configDialLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(saveconf))
                    .addGroup(configDialLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        errorDial.setTitle("An error occured");
        errorDial.setMinimumSize(new java.awt.Dimension(500, 300));
        errorDial.setModal(true);

        errorinformation.setColumns(20);
        errorinformation.setRows(5);
        jScrollPane2.setViewportView(errorinformation);

        closerrordialog.setText("Close");
        closerrordialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closerrordialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorDialLayout = new javax.swing.GroupLayout(errorDial.getContentPane());
        errorDial.getContentPane().setLayout(errorDialLayout);
        errorDialLayout.setHorizontalGroup(
            errorDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(errorDialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closerrordialog)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        errorDialLayout.setVerticalGroup(
            errorDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closerrordialog)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        configScanDial.setTitle("Give some informations before scanning");
        configScanDial.setMinimumSize(new java.awt.Dimension(480, 320));
        configScanDial.setModal(true);
        configScanDial.setResizable(false);
        configScanDial.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("GSM type");
        configScanDial.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        gsmtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsmtypeActionPerformed(evt);
            }
        });
        configScanDial.getContentPane().add(gsmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 145, -1));

        configurationfromscan.setText("Configuration");
        configurationfromscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationfromscanActionPerformed(evt);
            }
        });
        configScanDial.getContentPane().add(configurationfromscan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 145, -1));

        jLabel8.setText("RTL-SDR Device");
        configScanDial.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        StartScanBtnDial.setText("Scan now");
        StartScanBtnDial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartScanBtnDialActionPerformed(evt);
            }
        });
        configScanDial.getContentPane().add(StartScanBtnDial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        performingScan.setVisible(false);
        performingScan.setIcon(new javax.swing.ImageIcon("/root/NetBeansProjects/topguw2/src/main/resources/oader_blue_512.gif")); // NOI18N
        performingScan.setText("Performing the scan, please wait ");
        configScanDial.getContentPane().add(performingScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        workspaceLocation.setBackground(java.awt.Color.lightGray);
        workspaceLocation.setDialogTitle("Choose your workspace");
        workspaceLocation.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        workspaceLocation.setVisible(false);

        sniffcellDial.setTitle("Sniff a cell");
        sniffcellDial.setMinimumSize(new java.awt.Dimension(400, 300));
        sniffcellDial.setResizable(false);

        jLabel12.setText("Select the cell");

        cellsForSniffing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cellsForSniffing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellsForSniffingActionPerformed(evt);
            }
        });

        jLabel13.setText("RTL-SDR Conf");

        btnconf2.setText("Configuration");
        btnconf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconf2ActionPerformed(evt);
            }
        });

        startSniffing.setText("Sniff");
        startSniffing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSniffingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sniffcellDialLayout = new javax.swing.GroupLayout(sniffcellDial.getContentPane());
        sniffcellDial.getContentPane().setLayout(sniffcellDialLayout);
        sniffcellDialLayout.setHorizontalGroup(
            sniffcellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sniffcellDialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startSniffing)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sniffcellDialLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(sniffcellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(90, 90, 90)
                .addGroup(sniffcellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnconf2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cellsForSniffing, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        sniffcellDialLayout.setVerticalGroup(
            sniffcellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sniffcellDialLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(sniffcellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cellsForSniffing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(sniffcellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btnconf2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(startSniffing)
                .addGap(36, 36, 36))
        );

        cfileLocation.setFileFilter(new FileNameExtensionFilter(".cfile .CFILE", "CFILE", "cfile"));

        setACellDial.setTitle("Set a cell manually");
        setACellDial.setMinimumSize(new java.awt.Dimension(404, 249));
        setACellDial.setModal(true);
        setACellDial.setResizable(false);

        freqLblDial.setText("Frequency");

        frequencySetACellDial.setText("Hz");

        arfcnLblDial.setText("ARFCN ");

        gsmTYpeCellDial.setText("GSM type");

        gsmtypeSetACellDial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsmtypeSetACellDial1ActionPerformed(evt);
            }
        });

        setACellDialSaveBtn.setText("Save");
        setACellDialSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setACellDialSaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setACellDialLayout = new javax.swing.GroupLayout(setACellDial.getContentPane());
        setACellDial.getContentPane().setLayout(setACellDialLayout);
        setACellDialLayout.setHorizontalGroup(
            setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setACellDialLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(freqLblDial)
                    .addComponent(arfcnLblDial)
                    .addComponent(gsmTYpeCellDial))
                .addGap(99, 99, 99)
                .addGroup(setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gsmtypeSetACellDial1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(frequencySetACellDial)
                        .addComponent(arfcnSetACellDial, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setACellDialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setACellDialSaveBtn)
                .addGap(161, 161, 161))
        );
        setACellDialLayout.setVerticalGroup(
            setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setACellDialLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freqLblDial)
                    .addComponent(frequencySetACellDial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arfcnLblDial)
                    .addComponent(arfcnSetACellDial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(setACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gsmTYpeCellDial)
                    .addComponent(gsmtypeSetACellDial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(setACellDialSaveBtn)
                .addGap(29, 29, 29))
        );

        sniffACellLblDial.setText("Select which gsm cell you want to sniff : ");

        selectCellToSniff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        startsniffBtnDial.setText("Start sniff");
        startsniffBtnDial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startsniffBtnDialActionPerformed(evt);
            }
        });

        configurationRtlSniffDial.setText("Configuration");
        configurationRtlSniffDial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationRtlSniffDialActionPerformed(evt);
            }
        });

        jLabel14.setText("RTL-SDR Device");

        javax.swing.GroupLayout sniffACellDialLayout = new javax.swing.GroupLayout(sniffACellDial.getContentPane());
        sniffACellDial.getContentPane().setLayout(sniffACellDialLayout);
        sniffACellDialLayout.setHorizontalGroup(
            sniffACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sniffACellDialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sniffACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sniffACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(sniffACellDialLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(configurationRtlSniffDial))
                        .addComponent(sniffACellLblDial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectCellToSniff, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(startsniffBtnDial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sniffACellDialLayout.setVerticalGroup(
            sniffACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sniffACellDialLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(sniffACellLblDial)
                .addGap(38, 38, 38)
                .addComponent(selectCellToSniff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(sniffACellDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configurationRtlSniffDial)
                    .addComponent(jLabel14))
                .addGap(37, 37, 37)
                .addComponent(startsniffBtnDial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Topguw v2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        scanCellsBtn.setText("Scan for cells");
        scanCellsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanCellsBtnActionPerformed(evt);
            }
        });

        sniffCellBtn.setText("Sniff a cell");
        sniffCellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sniffCellBtnActionPerformed(evt);
            }
        });

        setACellBtn.setText("Set a cell");
        setACellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setACellBtnActionPerformed(evt);
            }
        });

        headerLogo.setFont(new java.awt.Font("Lato Black", 0, 60)); // NOI18N
        headerLogo.setText("TopGuw");

        programDescription.setText("Advanced tool for GSM");

        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        configBtn.setText("Configuration");
        configBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configBtnActionPerformed(evt);
            }
        });

        openCfileBtn.setText("Open a cfile ");
        openCfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCfileBtnActionPerformed(evt);
            }
        });

        performAnalyseBtn.setText("Perform analyse");
        performAnalyseBtn.setEnabled(false);
        performAnalyseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performAnalyseBtnActionPerformed(evt);
            }
        });

        activityLog.setContentType("text/html"); // NOI18N
        activityLog.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    \n  </body>\n</html>\n");
        jScrollPane3.setViewportView(activityLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerLogo)
                        .addGap(34, 34, 34)
                        .addComponent(programDescription)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(performAnalyseBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(openCfileBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(scanCellsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sniffCellBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(setACellBtn))
                                    .addComponent(cfileNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                                .addComponent(configBtn)
                                .addGap(32, 32, 32)
                                .addComponent(aboutBtn)))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(headerLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(programDescription)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scanCellsBtn)
                    .addComponent(sniffCellBtn)
                    .addComponent(setACellBtn)
                    .addComponent(aboutBtn)
                    .addComponent(configBtn))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openCfileBtn)
                    .addComponent(cfileNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(performAnalyseBtn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setACellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setACellBtnActionPerformed
        setACellDial.setVisible(true);
    }//GEN-LAST:event_setACellBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        aboutDial.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void closeAboutDialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAboutDialActionPerformed
        aboutDial.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeAboutDialActionPerformed

    private void saveconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveconfActionPerformed
        if (ppmconf.getText() != null && ppmconf.getText().length() > 0) {
            confRtl.setPpm(Integer.parseInt(ppmconf.getText()));
        }
        if (samplerateconf.getText() != null && samplerateconf.getText().length() > 0) {
            confRtl.setPpm(Integer.parseInt(samplerateconf.getText()));
        }
        if (gainconf.getText() != null && gainconf.getText().length() > 0) {
            confRtl.setPpm(Integer.parseInt(gainconf.getText()));
        }
        configDial.setVisible(false);
    }//GEN-LAST:event_saveconfActionPerformed

    private void scanCellsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanCellsBtnActionPerformed
        // show configuration options available for the user
        configScanDial.setVisible(true);
    }//GEN-LAST:event_scanCellsBtnActionPerformed

    private void configBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configBtnActionPerformed
        // open configuration
        configDial.setVisible(true);
    }//GEN-LAST:event_configBtnActionPerformed

    private void closerrordialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closerrordialogActionPerformed
        errorDial.setVisible(false);
        // erase the error for the .. next
        errorinformation.setText("");
    }//GEN-LAST:event_closerrordialogActionPerformed

    private void StartScanBtnDialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartScanBtnDialActionPerformed

        // show scan options
        performingScan.setVisible(true);
        StartScanBtnDial.setVisible(false);
        System.err.println(gsmtype.getSelectedItem().toString());
        try {
            // launch the scan
            cells = Scanner.getGsmCells(gsmtype.getSelectedItem().toString(), confRtl);
            if (cells.isEmpty()) {
                performingScan.setText("No cell have been found.");
                StartScanBtnDial.setVisible(true);
            } else {
                performingScan.setText("Founded cells have been register. Windows will close.");
                Thread.sleep(2500);
                configScanDial.setVisible(false);
            }
            performingScan.setIcon(null);
        } catch (IOException | RtlsdrError e) {
            errorinformation.setText(e.getMessage());
            errorDial.setVisible(true);
            performingScan.setText("Scan have failed.");
            performingScan.setIcon(null);
            StartScanBtnDial.setVisible(true);
        } catch (InterruptedException ex) {
            // Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_StartScanBtnDialActionPerformed

    private void configurationfromscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationfromscanActionPerformed
        configDial.setVisible(true);
    }//GEN-LAST:event_configurationfromscanActionPerformed

    private void gsmtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsmtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsmtypeActionPerformed

    private void sniffCellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sniffCellBtnActionPerformed
        if (cells == null || cells.isEmpty()) {
            errorinformation.setText("There is no cells found. Please scan or enter manually a cell.");
            errorDial.setVisible(true);
        } else {
            for (Cell c : cells) {
                selectCellToSniff.addItem(c.toString());
            }
        }
        // TODO make the windows
    }//GEN-LAST:event_sniffCellBtnActionPerformed

    private void setWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setWorkspaceActionPerformed
        workspaceLocation.setVisible(true);
        int result = workspaceLocation.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            workspace = new File(workspaceLocation.getSelectedFile().getAbsolutePath());
        } else {
            // TODO
        }
        // put the text on the window
        currentWorkspaceLbl.setText(workspace.toString());
    }//GEN-LAST:event_setWorkspaceActionPerformed

    private void btnconf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconf2ActionPerformed
        // open configuration
        configDial.setVisible(true);
    }//GEN-LAST:event_btnconf2ActionPerformed

    private void startSniffingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSniffingActionPerformed
        // TODO 
        // - instantiate cuCell var
        // - use Capture class from topguw api
        // - add a button to make the possibility to stop sniffing
        
    }//GEN-LAST:event_startSniffingActionPerformed

    private void cellsForSniffingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellsForSniffingActionPerformed
        // populate the gsm type combobox
        for (String s : Cell.BANDS) {
            gsmtype.addItem(s);
        }
    }//GEN-LAST:event_cellsForSniffingActionPerformed

    private void openCfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCfileBtnActionPerformed
        cfileLocation.setVisible(true);
        int result = cfileLocation.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            cfile = new File(cfileLocation.getSelectedFile().getAbsolutePath());
            cfileNameLbl.setText(cfile.getName());
            performAnalyseBtn.setEnabled(true);
        } else {
            // DO NOTHING
        }
    }//GEN-LAST:event_openCfileBtnActionPerformed

    private void performAnalyseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performAnalyseBtnActionPerformed
        // - instanciate the cell whose the capture file have been 
        
        
        Utils.performAnalyse(cfile, workspace, confRtl, cuCell, activityLog);
    }//GEN-LAST:event_performAnalyseBtnActionPerformed

    private void gsmtypeSetACellDial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsmtypeSetACellDial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsmtypeSetACellDial1ActionPerformed

    private void setACellDialSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setACellDialSaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setACellDialSaveBtnActionPerformed

    private void configurationRtlSniffDialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationRtlSniffDialActionPerformed
        configDial.setVisible(true);
    }//GEN-LAST:event_configurationRtlSniffDialActionPerformed

    private void startsniffBtnDialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startsniffBtnDialActionPerformed
        // TODO sniff the cell :
        Cell cell = Cell.stringTo(selectCellToSniff.getSelectedItem().toString());
        
        Utils.performAnalyse(cfile, workspace, confRtl, cell, activityLog);
        
        
        // - use Capture from the api
    }//GEN-LAST:event_startsniffBtnDialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartScanBtnDial;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JDialog aboutDial;
    private javax.swing.JTextPane activityLog;
    private javax.swing.JLabel arfcnLblDial;
    private javax.swing.JTextField arfcnSetACellDial;
    private javax.swing.JButton btnconf2;
    private javax.swing.JComboBox<String> cellsForSniffing;
    private javax.swing.JFileChooser cfileLocation;
    private javax.swing.JLabel cfileNameLbl;
    private javax.swing.JButton closeAboutDial;
    private javax.swing.JButton closerrordialog;
    private javax.swing.JButton configBtn;
    private javax.swing.JDialog configDial;
    private javax.swing.JDialog configScanDial;
    private javax.swing.JButton configurationRtlSniffDial;
    private javax.swing.JButton configurationfromscan;
    private javax.swing.JLabel currentWorkspaceLbl;
    private javax.swing.JDialog errorDial;
    private javax.swing.JTextArea errorinformation;
    private javax.swing.JLabel freqLblDial;
    private javax.swing.JTextField frequencySetACellDial;
    private javax.swing.JFormattedTextField gainconf;
    private javax.swing.JLabel gsmTYpeCellDial;
    private javax.swing.JComboBox<String> gsmtype;
    private javax.swing.JComboBox<String> gsmtypeSetACellDial1;
    private javax.swing.JLabel headerLogo;
    private javax.swing.JTextPane infoabout;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton openCfileBtn;
    private javax.swing.JButton performAnalyseBtn;
    private javax.swing.JLabel performingScan;
    private javax.swing.JFormattedTextField ppmconf;
    private javax.swing.JLabel programDescription;
    private javax.swing.JFormattedTextField samplerateconf;
    private javax.swing.JButton saveconf;
    private javax.swing.JButton scanCellsBtn;
    private javax.swing.JComboBox<String> selectCellToSniff;
    private javax.swing.JButton setACellBtn;
    private javax.swing.JDialog setACellDial;
    private javax.swing.JButton setACellDialSaveBtn;
    private javax.swing.JButton setWorkspace;
    private javax.swing.JDialog sniffACellDial;
    private javax.swing.JLabel sniffACellLblDial;
    private javax.swing.JButton sniffCellBtn;
    private javax.swing.JDialog sniffcellDial;
    private javax.swing.JButton startSniffing;
    private javax.swing.JButton startsniffBtnDial;
    private javax.swing.JFileChooser workspaceLocation;
    // End of variables declaration//GEN-END:variables
}
